

workflows:
  my-workflow:
    name: backendless
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
        - pattern: develop
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Build Android APK
          working_directory: android
          script: ./gradlew assembleRelease
          artifacts:
            - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - joko.mzee@gmail.com
      scripts:
        - echo 'Post-publish script'
